### ISSUE TITLE
Enhance esx_system_resource resource type to ensure mutually exclusivity of parameters

### ISSUE THREAD

**Issue by gjngeldenhuis** [vmware/vmware-vcenter#171]
* `cpu_unlimited`: Enable unlimited CPU resources. Can't be used in conjunction with `cpu_limit`
* `memory_unlimited`: Enable unlimited Memory resources. Can't be used in conjunction with `memory_limit`

The above should be enforced in the resource type.

**Comment by crayfishx** [comment]
@gjngeldenhuis I see what  you mean, but I also don't like the way the whole thing is implemented.

Looking at the code - the type has a _property_ of `cpu_limit` and `memory_limit`.   To make them unlimited they need to be set to `-1` (as far as the API is concerned).  The type has some unorthodox behaviour as it tries to override the value of `@resource[:cpu_limit]` from the parameter `cpu_unlimited`

That is pretty (very) kludgy, and doesn't make the type behave as you'd expect...

```
2.0.0-p481 :006 > Puppet::Type.type(:esx_system_resource).new(:name => 'foo', :cpu_unlimited => true)[:cpu_limit]
 => nil
```

Let's have a closer look at the type.....

```puppet
  newparam(:cpu_unlimited) do
    desc "Enable unlimited CPU resources"
    newvalues(:true,:false)
    munge do |value|
      if value == 'true'
        @resource[:cpu_limit] = -1
      elsif value == 'false' && !(@resource[:cpu_limit])
        @resource[:cpu_limit] = 0
      end
    end
  end
```

Bearing in mind that `munge` will only get called if we have declared the attribute, and the `cpu_limit` attribute has no default value, there are *three* possible outcomes here:

`esx_system_resource { 'foo': } `  => `@resource[:cpu_limit] == nil`
`esx_system_resource { 'foo': cpu_unlimited => false } `  => `@resource[:cpu_limit] == 0`
`esx_system_resource { 'foo': cpu_unlimited => true  } `  => `@resource[:cpu_limit] == -1`

This is all pretty weird and inviting unwanted behaviour.   IMHO a much better way of handling this would be to deprecate the `cpu_unlimited` parameter and make `unlimited` an acceptable value for the `cpu_limit` attribute... something like;

```puppet
  newproperty(:cpu_limit) do
    desc "CPU limit in MHz"
    newvalues(/\d{1,}/, "unlimited")
    munge do |value|
      value = -1 if value == "unlimited"
      value
    end
  end
```

Now we get the following behaviour

```
2.0.0-p481 :001 > Puppet::Type.type(:esx_system_resource).new(:name => 'foo', :cpu_limit => '10')[:cpu_limit]
 => "10"
2.0.0-p481 :002 > Puppet::Type.type(:esx_system_resource).new(:name => 'foo', :cpu_limit => 'unlimited')[:cpu_limit]
 => -1
```

It's an API breaking change to the resource type, but IMO, a lot easier to understand and avoids nasty hacks with `@resource[]`

(all of the above applies to `memory_limit` too)
