### ISSUE TITLE
More meaningfull error messages when Transport is not specified

### ISSUE THREAD

**Issue by gjngeldenhuis** [vmware/vmware-vcenter#186]
When transport is not specified for a resource the error message can be a bit cryptic. Having a clearer message will help to more quickly get to the bottom of a problem in the catalogue. Typical error message would be: 
```
Error: /Stage[main]/Main/Esx_vswitch[esx00001:testSwitch]: Could not evaluate: undefined method `server' for nil:NilClass
```

This is issue is intended for @crayfishx

**Comment by crayfishx** [comment]
@gjngeldenhuis you can close this now
