### ISSUE TITLE
Porting of general enhancements from the Dell module

### ISSUE THREAD

**Issue by gjngeldenhuis** [vmware/vmware-vcenter#188]
This ticket is intended for @crayfishx 

The following PRs would be useful to consider porting to this module.
- https://github.com/dell-asm/vmware-vcenter/pull/9
- https://github.com/dell-asm/vmware-vcenter/pull/16
- https://github.com/dell-asm/vmware-vcenter/pull/17
- https://github.com/dell-asm/vmware-vcenter/pull/37
- https://github.com/dell-asm/vmware-vcenter/pull/39
- https://github.com/dell-asm/vmware-vcenter/pull/43
- https://github.com/dell-asm/vmware-vcenter/pull/46
- https://github.com/dell-asm/vmware-vcenter/pull/50
- https://github.com/dell-asm/vmware-vcenter/pull/55
- https://github.com/dell-asm/vmware-vcenter/pull/60
- https://github.com/dell-asm/vmware-vcenter/pull/62
- https://github.com/dell-asm/vmware-vcenter/pull/63
- https://github.com/dell-asm/vmware-vcenter/pull/64
- https://github.com/dell-asm/vmware-vcenter/pull/65
- https://github.com/dell-asm/vmware-vcenter/pull/66
- https://github.com/dell-asm/vmware-vcenter/pull/69
- https://github.com/dell-asm/vmware-vcenter/pull/70
- https://github.com/dell-asm/vmware-vcenter/pull/77
- https://github.com/dell-asm/vmware-vcenter/pull/82 ( Possibly )
- https://github.com/dell-asm/vmware-vcenter/pull/94

**Comment by crayfishx** [comment]
@gjngeldenhuis From your list, I've submitted PR's for the ones that are valid;

dell-asm#9  Invalid no esx_fc_multiple_path_config type
dell-asm#16 Invalid no esx_portgroup type
dell-asm#17 Already implemented
dell-asm#37 #192 
dell-asm#39 #193 
dell-asm#43 Invalid no esx_portgroup type
dell-asm#46 Invalid no esx_mem type
dell-asm#50 Invalid no esx_mem type
dell-asm#55 Invalid no esx_portgroup type
dell-asm#60 #194 
dell-asm#62 Invalid (never merged, bad PR)
dell-asm#63 #194 
dell-asm#64 #194 
dell-asm#65 Invalid no esx_mem type
dell-asm#66 #194 
dell-asm#69 #195 
dell-asm#70 Duplicate of 69?
dell-asm#77 #196 
dell-asm#82 On hold
dell-asm#94 #197

**Comment by gjngeldenhuis** [comment]
Great work!
