### ISSUE TITLE
Create resource type to support vcenter advanced settings

### ISSUE THREAD

**Issue by gjngeldenhuis** [vmware/vmware-vcenter#209]
Currently there appears to be no way of setting vcenter advanced settings, only esxi advanced settings. Typical settings to be set would be: 

- vpxd.certmgmt.certs.minutesBefore
- VirtualCenter.ManagedIP

These settings would not appear on a cleanly installed vcenter but only after it is set. 

The Screenshot gives an example of the default settings.
![screen shot 2016-08-11 at 12 01 48](https://cloud.githubusercontent.com/assets/192423/17586766/8b678d22-5fbb-11e6-9b2b-db487b15f646.png)

**Comment by gjngeldenhuis** [comment]
This script is an example of setting the settings: https://github.com/lamw/vghetto-scripts/blob/master/perl/vCenterAdvSettingMgmt.pl

This API call can be found at: http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.option.OptionManager.html&resultof=%22OptionManager%22%20%22optionmanag%22%20

**Comment by maniacmurphy** [comment]
We currently manage vCenter settings with the vc_vpx_settings resource. I know for a fact it has been used to set event.maxAgeEnabled, event.maxAge, task.maxAgeEnabled, and task.maxAge. I am pretty sure it uses the referenced API too.

You can see an example manifest at https://github.com/vmware/vmware-vcenter/blob/master/tests/vc_vpxsettings.pp

where $vpx_settings would match this:

```
        $vpxsettings = {
          'event.maxAgeEnabled' => true,
          'event.maxAge'             => 180,
          'task.maxAgeEnabled'   => true,
          'task.maxAge'               => 180,
        }
```

**Comment by gjngeldenhuis** [comment]
I will test it and give it a go. Is it worthwhile to rename it to something more generic? vCenterAdvancedSettings or something along that vein?

**Comment by gjngeldenhuis** [comment]
So currently trying to set ```vpxd.certmgmt.certs.minutesBefore' => 10``` give the following error:
```
Error: /Stage[main]/Main/Vc_vpxsettings[vcv0000x.pod0000x.sys0000x.il2management.local]: Could not evaluate: key: vpxd.certmgmt.certs.minutesBefore was not found,
           1. browse to https://<vcenter>/mob/?moid=ServiceInstance&method=retrieveContent
           2. click on Invoke Method
           3. select VpxSettings and check if your property is listed as setting[vpxd.certmgmt.certs.minutesBefore],
              ( this should exactly match whats inside setting[] )
```

It might be related to the version of vcenter that I am using.

**Comment by maniacmurphy** [comment]
I tested this vc_vpxsettings test manifest against a 5.5 Build 300241 and 6.0 Build 3634794. The data.pp looked like this:

```
$vcenter = {
  'server' => 'mgmt-vc0',
  'username' => 'root',
  'password' => 'vmware',
  'options'  => {
    'insecure' => true,
    'rev'      => 5.5
  }
}

$vpx_settings = {
  'vpxd.certmgmt.certs.minutesBefore' => 10,
}
```

It succeeded against the 6.0 but failed with the same error against 5.5. When looking in the MOB, I don't see that setting under 5.5

**Comment by gjngeldenhuis** [comment]
I can confirm that against the latest update it worked perfect well for me too.
